import { EventTypes } from '@/core/events/eventTypes.js';

export const INTENT_CAPS = {
  // node
  [EventTypes.NODE_CREATE]: ['node:create'],
  [EventTypes.NODE_UPDATE]: ['node:mutate'],
  [EventTypes.NODE_DELETE]: ['node:delete'],
  [EventTypes.LAYOUT_CONVERT]: ['node:create'],
  [EventTypes.VECTOR_CREATE]: ['vector:create'],
  [EventTypes.VECTOR_UPDATE]: ['vector:mutate'],
  [EventTypes.VECTOR_DELETE]: ['vector:delete'],
  [EventTypes.AI_REQUEST_ENQUEUE]: ['ai:generate'],
  [EventTypes.STATE_MACHINE_CREATE]: ['state-machine:author'],
  [EventTypes.STATE_MACHINE_UPDATE]: ['state-machine:author'],
  [EventTypes.STATE_MACHINE_DELETE]: ['state-machine:author'],
  [EventTypes.STATE_MACHINE_SET_ACTIVE]: ['state-machine:author'],
  [EventTypes.STATE_MACHINE_PARAMETER_SET]: ['state-machine:author'],
  [EventTypes.STATE_MACHINE_TRANSITION]: ['app:state-machine'],
  [EventTypes.NAVIGATION_NAVIGATE]: ['app:navigate'],

  // tokens / themes
  [EventTypes.TOKEN_CREATE]: ['token:author'],
  [EventTypes.TOKEN_SET]: ['token:author'],
  [EventTypes.TOKEN_DELETE]: ['token:author'],
  [EventTypes.TOKEN_ALIAS_SET]: ['token:author'],
  [EventTypes.THEME_CREATE]: ['theme:author'],
  [EventTypes.THEME_SWITCH]: ['theme:author'],
  [EventTypes.TOKEN_VERSION_TAG]: ['token:version'],
  [EventTypes.TOKEN_VERSION_FORK]: ['token:version'],
  [EventTypes.TOKEN_VERSION_MERGE]: ['token:version'],
  [EventTypes.TOKEN_VERSION_ROLLBACK]: ['token:version'],
  [EventTypes.TOKEN_REVIEW_SUBMIT]: ['token:review'],
  [EventTypes.TOKEN_REVIEW_APPROVE]: ['token:review'],
  [EventTypes.TOKEN_REVIEW_REJECT]: ['token:review'],
  [EventTypes.TOKEN_REVIEW_REQUEST_CHANGES]: ['token:review'],

  // behavior authoring (v1)
  [EventTypes.BEHAVIOR_STATE_CREATE]: ['node:mutate'],
  [EventTypes.BEHAVIOR_STATE_UPDATE]: ['node:mutate'],
  [EventTypes.BEHAVIOR_STATE_DELETE]: ['node:mutate'],

  // timeline / animation
  [EventTypes.TIMELINE_TRACK_CREATE]: ['timeline:edit'],
  [EventTypes.TIMELINE_TRACK_DELETE]: ['timeline:edit'],
  [EventTypes.TIMELINE_TRACK_REORDER]: ['timeline:edit'],
  [EventTypes.TIMELINE_TRACK_CHANNEL_ASSIGN]: ['timeline:edit'],
  [EventTypes.TIMELINE_TRACK_LOCK_TOGGLE]: ['timeline:edit'],
  [EventTypes.TIMELINE_TRACK_BLEND_MODE_SET]: ['timeline:edit'],
  [EventTypes.TIMELINE_GROUP_CREATE]: ['timeline:edit'],
  [EventTypes.TIMELINE_GROUP_DELETE]: ['timeline:edit'],
  [EventTypes.TIMELINE_GROUP_LOCK_TOGGLE]: ['timeline:edit'],
  [EventTypes.TIMELINE_GROUP_COLLAPSE_TOGGLE]: ['timeline:edit'],
  [EventTypes.TIMELINE_GROUP_TRACK_ASSIGN]: ['timeline:edit'],
  [EventTypes.TIMELINE_GROUP_TRACK_UNASSIGN]: ['timeline:edit'],
  [EventTypes.TIMELINE_KEYFRAME_ADD]: ['timeline:edit'],
  [EventTypes.TIMELINE_KEYFRAME_MOVE]: ['timeline:edit'],
  [EventTypes.TIMELINE_EVENT_ADD]: ['timeline:edit'],

  [EventTypes.ANIMATION_TRACK_CREATE]: ['timeline:edit'],
  [EventTypes.ANIMATION_TRACK_DELETE]: ['timeline:edit'],
  [EventTypes.ANIMATION_KEYFRAME_ADD]: ['keyframe:create'],
  [EventTypes.ANIMATION_KEYFRAME_CREATE]: ['keyframe:create'],
  [EventTypes.ANIMATION_KEYFRAME_UPDATE]: ['keyframe:mutate'],
  [EventTypes.ANIMATION_KEYFRAME_DELETE]: ['keyframe:mutate'],
  [EventTypes.MOTION_CLIP_CREATE]: ['timeline:edit'],
  [EventTypes.MOTION_CLIP_UPDATE]: ['timeline:edit'],
  [EventTypes.MOTION_CLIP_DELETE]: ['timeline:edit'],
  [EventTypes.MOTION_KEYFRAME_ADD]: ['keyframe:create'],
  [EventTypes.MOTION_KEYFRAME_UPDATE]: ['keyframe:mutate'],
  [EventTypes.MOTION_KEYFRAME_DELETE]: ['keyframe:mutate'],

  // rigging
  [EventTypes.RIG_CREATE]: ['rig:author'],
  [EventTypes.RIG_UPDATE]: ['rig:author'],
  [EventTypes.RIG_DELETE]: ['rig:author'],
  [EventTypes.RIG_SET_ACTIVE]: ['rig:author'],
  [EventTypes.RIG_CONTROLLER_CREATE]: ['rig:author'],
  [EventTypes.RIG_CONTROLLER_UPDATE]: ['rig:author'],
  [EventTypes.RIG_CONTROLLER_DELETE]: ['rig:author'],
  [EventTypes.RIG_CONSTRAINT_CREATE]: ['rig:author'],
  [EventTypes.RIG_CONSTRAINT_UPDATE]: ['rig:author'],
  [EventTypes.RIG_CONSTRAINT_DELETE]: ['rig:author'],

  // sequencer
  [EventTypes.SEQUENCE_CREATE]: ['sequencer:author'],
  [EventTypes.SEQUENCE_UPDATE]: ['sequencer:author'],
  [EventTypes.SEQUENCE_DELETE]: ['sequencer:author'],
  [EventTypes.SEQUENCE_SET_ACTIVE]: ['sequencer:author'],
  [EventTypes.SEQUENCE_TRACK_CREATE]: ['sequencer:author'],
  [EventTypes.SEQUENCE_TRACK_UPDATE]: ['sequencer:author'],
  [EventTypes.SEQUENCE_TRACK_DELETE]: ['sequencer:author'],
  [EventTypes.SEQUENCE_CLIP_CREATE]: ['sequencer:author'],
  [EventTypes.SEQUENCE_CLIP_UPDATE]: ['sequencer:author'],
  [EventTypes.SEQUENCE_CLIP_DELETE]: ['sequencer:author'],
  [EventTypes.SEQUENCE_CLIP_MOVE]: ['sequencer:author'],
  [EventTypes.SEQUENCE_CLIP_TRIM]: ['sequencer:author'],
  [EventTypes.SEQUENCE_CLIP_SPLIT]: ['sequencer:author'],
  [EventTypes.MEDIA_ASSET_REGISTER]: ['sequencer:author'],
  [EventTypes.MEDIA_ASSET_UPDATE]: ['sequencer:author'],
  [EventTypes.MEDIA_ASSET_DELETE]: ['sequencer:author'],
  [EventTypes.EXPORT_TARGET_UPSERT]: ['export:run'],
  [EventTypes.EXPORT_TARGET_DELETE]: ['export:run'],
};
