name: "Phase 1 — Default State Display"
description: "Expose Default state visually (read-only)."
title: "[Phase 1] Default state UI"
labels: ["phase-1", "ui", "states"]
body:
  - type: checkboxes
    attributes:
      label: Rules
      options:
        - label: Default state is always visible
          required: true
        - label: Default state cannot be deleted or renamed
          required: true

  - type: checkboxes
    attributes:
      label: Acceptance Criteria
      options:
        - label: Default is visually distinct
        - label: UX communicates baseline clearly
