import { buildStaticHTML } from '../static/buildStaticHTML';

const STYLE_CSS = `/*
Theme Name: Dropple Export
Description: Structure-only theme generated by Dropple
Version: 0.1
*/
`;

const FUNCTIONS_PHP = `<?php
// Structure-only theme generated by Dropple.
// No scripts, styles, or hooks are registered here.
`;

const HEADER_PHP = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <?php wp_head(); ?>
</head>
<body>
`;

const FOOTER_PHP = `<?php wp_footer(); ?>
</body>
</html>
`;

export function buildWordPressTheme(droppleSpec, options = {}) {
    const html = buildStaticHTML(droppleSpec, options);
    const mainContent = extractMainContent(html);

    const indexPhp = [
        '<?php get_header(); ?>',
        '<main>',
        mainContent ? indent(mainContent, 2) : '',
        '</main>',
        '<?php get_footer(); ?>',
    ]
        .filter((line) => line !== '')
        .join('\n');

    return {
        'style.css': STYLE_CSS,
        'functions.php': FUNCTIONS_PHP,
        'header.php': HEADER_PHP,
        'footer.php': FOOTER_PHP,
        'index.php': indexPhp,
    };
}

function extractMainContent(html) {
    const match = html.match(/<main>([\s\S]*?)<\/main>/);
    if (!match) return '';
    return match[1].trim();
}

function indent(str, spaces) {
    const pad = ' '.repeat(spaces);
    return str
        .split('\n')
        .map((line) => (line ? pad + line : line))
        .join('\n');
}
